---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: theneva/lehmann-tech
          ports:
            - containerPort: 5678
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: unwanted-fun
spec:
  domains:
    - unwanted.fun
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: NodePort
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: blog
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blog
---

