kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
  - ingress-patch.yaml
  - managedcertificate-patch.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-json-patch.yaml
